### ISSUE TITLE
de.sonumina.javautil incompatibility with new ontologizer

### ISSUE THREAD

**Issue by julesjacobsen** [ontologizer/ontologizerlib#1]
Hi. This is great that you're moving the ontologizer code here and into maven central. For this reason I'd like to use this version in exomiser, so as not to have to rely on the Charite Jenkins server.

I tried replacing the old ontologizer.jar with the new ones but you've changed the package of ```Ontology``` and ```Term``` from ```ontologizer.go``` to ```ontologizer.ontology```. This makes complete sense, however it isn't compatible with things like the ```similarity.concepts.ResnikSimilarity``` or ```similarity.concepts.InformationContentObjectSimilarity``` from ```de.sonumina.javautil```

```xml
        <dependency>
            <groupId>de.sonumina</groupId>
            <artifactId>javautil</artifactId>
            <version>0.0.1</version>
        </dependency>
        <!--<dependency>-->
            <!--<groupId>ontologizer</groupId>-->
            <!--<artifactId>ontologizer</artifactId>-->
            <!--<version>0.0.1-SNAPSHOT</version>-->
        <!--</dependency>-->
        <dependency>
            <groupId>de.ontologizer</groupId>
            <artifactId>ontologizerlib-core</artifactId>
            <version>0.1</version>
        </dependency>
        <dependency>
            <groupId>de.ontologizer</groupId>
            <artifactId>ontologizerlib-io</artifactId>
            <version>0.1</version>
        </dependency>
```

Are you planning on moving this code into a new ontologizer similarity package? If not, could I request this happen at some point soon?

**Comment by sba1** [comment]
Yes, it is at least planned to unify all of this under this project / organization..

**Comment by julesjacobsen** [comment]
Awesome news - any idea about when you might start on this?

**Comment by iamkoehler** [comment]
BTW, the jenkins server has nothing to do with this

**Comment by iamkoehler** [comment]
You should have a look at https://github.com/Phenomics/ontolib

**Comment by julesjacobsen** [comment]
Now I'm completely confused. These are very similar projects, no?

**Comment by iamkoehler** [comment]
ping @holtgrewe

**Comment by holtgrewe** [comment]
Dear all,

after we realized that @sba1 has different aims than we (including to evolve quickly "on the go" with nightly releases and sticking to ByteString besides others), @drseb and I decided to start a clean project with a rewrite of the (immutable) data structures, I/O and algorithms at phenomics/ontolib.

We will maintain the latter library in the future and publish updates via Maven Central instead of making nightly builds available. Everyone is invited to contribute there. We already started to plan monthly phone conferences on larger changes to that library with @pnrobinson beginning this autumn.

Cheers,
Manuel

**Comment by julesjacobsen** [comment]
OK, so Phenomics/ontolib is a fork of which existing library?

**Comment by holtgrewe** [comment]
Phenomics/ontolib is a rewrite of ontologizerlib and the similarity library of @drseb

**Comment by iamkoehler** [comment]
P.S.: The aforementioned similarity library is what you use in Exomiser (javautil or javautil_pheno)

**Comment by julesjacobsen** [comment]
Sorry, I'm being obtuse - @drseb that's what I'm trying to figure out. These are the imported classes:
```java
import hpo.HPOutils;
import ontologizer.go.*;
import similarity.SimilarityUtilities;
import similarity.concepts.ResnikSimilarity;
import similarity.objects.InformationContentObjectSimilarity;
import sonumina.math.graph.SlimDirectedGraphView;
```
which come from these libraries:
```
<dependency>
    <groupId>de.sonumina</groupId>
    <artifactId>javautil</artifactId>
    <version>0.0.1</version>
</dependency>
<dependency>
    <groupId>ontologizer</groupId>
    <artifactId>ontologizer</artifactId>
    <version>0.0.1-SNAPSHOT</version>
</dependency>
```
although internally they seem to be a bit muddled.

I guess I can simply wait and use the new library when it's ready rather than trying to refactor now?

**Comment by holtgrewe** [comment]
@julesjacobsen Should we create an issue in Exomiser? I can have a look whether I can help you out there.

**Comment by julesjacobsen** [comment]
@holtgrewe maybe - but it might also be worth moving on to the next best thing and retiring phenix. Thanks for the offer.
